spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: demo
  password: demo

camunda:
  bpm:
    generic-properties:
      properties:
        historyTimeToLive: 5
    script-engine-name-javascript: graal.js

logging:
  file:
    path: ./logs/
    name: camunda-app.log
  level:
    root: INFO
    # It's helpful to set the logging level for the scripting engine specifically
    org:
      camunda:
        bpm:
          application: INFO
          engine:
            impl:
              scripting: INFO